## configmap object pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-object
  labels:
    app: my-cm-app
spec:
  containers:
  - name: my-cm-pod
    image: mysql
    ports:
            - name: sql
              containerPort: 3306
              protocol: TCP
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                configmapKeyRef:
                  name: my-configmap-cred
                  key: DB_PASS

## Secrets object pod
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret-object
  labels:
    app: my-secret-app
spec:
  containers:
    - name: my-secret-pod
      image: mysql
      ports:
      - name: sql
        containerPort: 3306
        protocol: TCP
      env:
      - name: "MYSQL_ROOT_PASSWORD"
        valueFrom:
          secretKeyRef:
            name: my-secret-cred
            key: DB_PASS