apiVersion: v1
kind: ConfigMap
metadata: 
  name: my-configmap-app
  labels:
    app: my-cm-app
spec:
  apiVersion: v1
  kind: Secret
  metadata:
    name:  secretName
  data:
     secretKey:  BASE64_ENCODED_VALUE
  type: Opaque