apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: nm-app
spec:
  template:
    metadata:
      name: deploy-app
      labels:
        app: nm-app
    spec:
      containers:
        - name: nm-app
          image: nginx
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 80
  replicas: 0
  selector:
    matchLabels:
      app: nm-app
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
