apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss-1
spec:
  template:
    metadata:
      labels:
        app: my-ss-app
      namespace: ns1
    spec:
      containers:
      - name: my-ss-app
        image: httpd
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

  selector:
    matchLabels:
      app: myapp
  replicas: 2
