apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss-app
spec:
  template:
    metadata:
      labels:
        app: my-ss-app
      namespace: ns1
    spec:
      containers:
        - name: my-ss-pod
          image: mysql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          env:
            key: "  MYSQL_ROOT"
  selector:
    matchLabels:
      app: my-ss-app
  replicas: 2
