apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-ss-1
spec:
  template:
    metadata:
      labels:
        app: my-ss-app
      namespace: ns1
    spec:
      containers:
      - name: my-ss
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web

  selector:
    matchLabels:
      app: myapp
  replicas: 2
