
# apiVersion: v1
# kind: Service
# metadata:
#   name: laptop-app-service
# spec:
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: laptop-app
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mobile-app-service
# spec:
#   ports:
#     - name: http
#       port: 80
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: mobile-app
