FROM centos:7
RUN yum install httpd -y
RUN mkdir /var/www/html/mobile/
RUN echo "<h1>WELCOME TO Mobile Page" > /var/www/html/mobile/index.html
RUN chmod 777 /var/www/html/mobile/
EXPOSE 80
ENTRYPOINT ["httpd", "-DFOREGROUND"]