
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mobile-obejct
  labels:
    app: mobile-app
spec:
  template:
    metadata:
      name: mobile-app
      labels:
        app: mobile-app
    spec:
      containers:
        - name: my-mobile-pod
          image: /
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: mobile-app
  strategy:
    type: RollingUpdate
