apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-project-ingress
  labels:
    name: project-ingress
spec:
  rules:
    - host: <Host>
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: <Service>
                port:
                  number: <Port>
