apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-project-ingress
  labels:
    name: project-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: home-app-service
      port:
        number: 80
  rules:
    - host: karad.clou
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: <Service>
                port:
                  number: <Port>
