apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-home
  labels:
    app: home-app
spec:
  template:
    metadata:
      name: home-app
      labels:
        app: home-app
    spec:
      containers:
        - name: my-home-pod
          image: /
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: home-app
  strategy:
    type: RollingUpdate

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-laptop-obejct
  labels:
    app: laptop-app
spec:
  template:
    metadata:
      name: laptop-app
      labels:
        app: laptop-app
    spec:
      containers:
        - name: my-laptop-pod
          image: /
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: laptop-app
  strategy:
    type: RollingUpdate

---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mobile-obejct
  labels:
    app: mobile-app
spec:
  template:
    metadata:
      name: deploy-app
      labels:
        app: nm-app
    spec:
      containers:
        - name: my-deploy-pod
          image: nginx
          ports:
            - name: nginx
              protocol: TCP
              containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: nm-app
  strategy:
    type: RollingUpdate
