apiVersion: v1
kind: Service
metadata:
  name: home-app-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: home-app

---
apiVersion: v1
kind: Service
metadata:
  name: cloth-app-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: cloth-app

---
apiVersion: v1
kind: Service
metadata:
  name: mobile-app-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: mobile-app