apiVersion: v1
kind: Service
metadata:
  name: home-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: home-app
---
apiVersion: v1
kind: Service
metadata:
  name: lap-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: laptop-app
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-app-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mobile-app
